export const REQUEST_GROUP_CITIES = "REQUEST_GROUP_CITIES ";

//Layout
export const TOGGLE_LAYOUT_THEME_ACTION = "TOGGLE_LAYOUT_THEME_ACTION ";

//API
export const CALL_SEVERAL_CITY_IDS_STARTED = 'CALL_SEVERAL_CITY_IDS_STARTED';
export const CALL_SEVERAL_CITY_IDS_SUCCESS = 'CALL_SEVERAL_CITY_IDS_SUCCESS';
export const CALL_SEVERAL_CITY_IDS_FAILURE = 'CALL_SEVERAL_CITY_IDS_FAILURE';

export const CALL_ONE_CITY_STARTED = 'CALL_ONE_CITY_STARTED';
export const CALL_ONE_CITY_SUCCESS = 'CALL_ONE_CITY_SUCCESS';
export const CALL_ONE_CITY_FAILURE = 'CALL_ONE_CITY_FAILURE';

export const FIND_CITIES_CUR_WEATHER_STARTED = 'FIND_CITIES_CUR_WEATHER_STARTED';
export const FIND_CITIES_CUR_WEATHER_SUCCESS = 'FIND_CITIES_CUR_WEATHER_SUCCESS';
export const FIND_CITIES_CUR_WEATHER_FAILURE = 'FIND_CITIES_CUR_WEATHER_FAILURE';
export const FIND_CITIES_CUR_WEATHER_RESET = 'FIND_CITIES_CUR_WEATHER_RESET';

//GEOIP
export const CALL_GEOIP_SUCCESS = 'CALL_GEOIP_SUCCESS';
export const CALL_GEOIP_STARTED = 'CALL_GEOIP_STARTED';
export const CALL_GEOIP_FAILURE = 'CALL_GEOIP_FAILURE';