export const REQUEST_GROUP_CITIES = "REQUEST_GROUP_CITIES ";

//Layout
export const TOGGLE_LAYOUT_THEME_ACTION = "TOGGLE_LAYOUT_THEME_ACTION ";

//API
export const CALL_SEVERAL_CITY_IDS_STARTED = 'CALL_SEVERAL_CITY_IDS_STARTED';
export const CALL_SEVERAL_CITY_IDS_SUCCESS = 'CALL_SEVERAL_CITY_IDS_SUCCESS';
export const CALL_SEVERAL_CITY_IDS_FAILURE = 'CALL_SEVERAL_CITY_IDS_FAILURE';
